package com.electrahub.ocpp.domain.enums;

public enum OcppErrorCode {
    NOT_IMPLEMENTED,
    NOT_SUPPORTED,
    INTERNAL_ERROR,
    PROTOCOL_ERROR,
    SECURITY_ERROR,
    FORMATION_VIOLATION,
    PROPERTY_CONSTRAINT_VIOLATION,
    OCCURENCE_CONSTRAINT_VIOLATION,
    TYPE_CONSTRAINT_VIOLATION,
    GENERIC_ERROR
}
