package com.electrahub.ocpp.domain.enums;

public enum OcppAction {
    BOOT_NOTIFICATION,
    HEARTBEAT,
    AUTHORIZE,
    START_TRANSACTION,
    STOP_TRANSACTION,
    METER_VALUES,
    STATUS_NOTIFICATION,
    DATA_TRANSFER,
    TRANSACTION_EVENT,
    REMOTE_START_TRANSACTION,
    REMOTE_STOP_TRANSACTION,
    RESET,
    UNLOCK_CONNECTOR,
    SET_CHARGING_PROFILE,
    CHANGE_CONFIGURATION,
    GET_CONFIGURATION,
    TRIGGER_MESSAGE
}
